### ISSUE TITLE
Misleading citation

### ISSUE THREAD

**Issue by pavlikva** [lwang-astro/PeTar#26]
In the definition of the core radius:
 
def calcCoreRadius(self, particle):
        """ Calculate core radius, using Casertano & Hut (1985) method:

The method with squares, that is used to calculate the core radius, actually does not come from Casertano & Hut but from NBODY5. Check Sverre's book Eq.(15.4). Thanks!

**Comment by lwang-astro** [comment]
From Portegies Zwart et al. 2010 ARAA, "[The square is used rather than the first power, as originally suggested by Casertano & Hut (1985), to stabilize the algorithm and make it less sensitive to outliers.]". I think the citation to Casertano & Hut (1985) is not wrong, but I can add both references.

**Comment by pavlikva** [comment]
Thanks. I would include all three then: Cassertano & Hut, Sverre's book and Simon's paper.
