### ISSUE TITLE
Error in make on a MacBook Pro M2

### ISSUE THREAD

**Issue by marlito-gonaldo-byte** [lwang-astro/PeTar#53]
Hello,

I am trying to install PeTar on my MacBook Pro M2 2022 (macOS Sonoma 14.4.1), but I am having issue when I try to 'make'.

I did : `./configure --with-fdps-prefix=$HOME/Desktop/PBH/code/FDPS-7.0b --with-sdar-prefix=$HOME/Desktop/PBH/code/SDAR-master/ --prefix=$HOME/Desktop/PBH/code/install --with-arch=arm64`

Which seems to have worked just fine.

Then I tried to : `make install`
but it couldn't find the mpi library so I specified the path : `make CXXFLAGS="-I/opt/homebrew/Cellar/open-mpi/5.0.3_1/include" install`
And now I get a really long error message which comes down to : 
```
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make: *** [build/petar.mpi.omp] Error 1
```

(By the way I have another issue open about the usage of PeTar on a HPC, I have not yet be able to solve my issue and my slurm jobs are pending, in the mean time I would like to install it on my laptop)

**Comment by lwang-astro** [comment]
With only the message:
```
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make: *** [build/petar.mpi.omp] Error 1
```
I cannot identify the detail of the problem. 
I guess that your MPI compiler environment is not properly setuped that petar code cannot link the mpi library correctly. But it is not necessary to use MPI in the macbook, since it is useful for many CPU cores. For laptop, OpenMP is enough, you can switch off MPI to avoid the compiling issue by adding the configure option `with-mpi=no`
